Parking/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Parking.Models;
using Parking.EF;
using Parking.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Parking.Interfaces;
using ApplicationSettings;
using Parking.Code;

namespace Parking.Controllers
{
    [Authorize]
    public class HomeController : BaseController
    {
        ManageAutomaticParkingDates CheckCurrentDays = new ManageAutomaticParkingDates();
        private readonly UserManager<User> _userManager;
        IParkingManagement _parkingManagementManager;
        private readonly ApplicationDbContext _context;
        IParking _parkingManager;
        IParkingDetailsOnDate _parkingDetailsManager;

        public HomeController(ApplicationDbContext context, UserManager<User> userManager, SignInManager<User> signInManager, IParkingManagement parkingManagementManager, IParking parkingManager, IParkingDetailsOnDate parkingDetailsManager)
        {
            _userManager = userManager;
            _parkingManagementManager = parkingManagementManager;
            _parkingManager = parkingManager;
            _parkingDetailsManager = parkingDetailsManager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var allParkingData = CreateDataIfNeccesary().Result;
            var model = await PopulateModelWithDatabaseElements(allParkingData.ToList());

            return View(model);
        }

        private async Task<IEnumerable<ParkingAndDateRelationship>> CreateDataIfNeccesary()
        {
            var allPArkingData = _parkingManagementManager.GetTodayRecordsAsync().Result.ToList();

            if (!allPArkingData.Any())
            {
                int daysToAddInAdvance = 7;
                await CheckCurrentDays.CreateNextParkingDaysIfNeccesary(daysToAddInAdvance, _parkingManager, _parkingDetailsManager, _parkingManagementManager);
                allPArkingData = _parkingManagementManager.GetTodayRecordsAsync().Result.ToList();
            }

            return await _parkingManagementManager.GetTodayRecordsAsync();
        }

        private async Task<List<SpaceAndUserAssignmentIndex>> PopulateModelWithDatabaseElements(List<ParkingAndDateRelationship> allParkingData)
        {
            var model = new List<SpaceAndUserAssignmentIndex>();

            foreach (var item in allParkingData)
            {
                var userId = GetCurrentUser(_userManager).Id;

                var modelToAdd = new SpaceAndUserAssignmentIndex()
                {
                    ID = item.ID,
                    AssignedDate = item.ParkingDetailsOnDate.Date.ToShortDateString(),
                    AssignSpaceNumber = item.ParkingSpot.SpaceNumber,
                    AssignedUser = item.AssignedToUser?.Email,
                    CanThisUserfreeThisSpace = User.Identity.IsAuthenticated && item.AssignedToUser?.Id == userId,
                    Description = item.ParkingDetailsOnDate.Description,
                    DoesThisSpaceBelongToUser = item.ParkingSpot.PermanentlyAssignedToUserId == userId,
                    isThisSpacePArtiallybookedToday = item.ParkingDetailsOnDate.ApplyPartialBooking,
                    StartTimeIfPartial = item.ParkingDetailsOnDate.StartTimeIfPartial,
                    EndTimeIfPartial = item.ParkingDetailsOnDate.EndTimeIfPartial,
                };

                model.Add(modelToAdd);
            }

            return model;
        }
    }
}

Parking/Controllers/ManageUserAssignmentsToParkingController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Parking.EF;
using Parking.Entities;
using Parking.Models;
using Microsoft.AspNetCore.Identity;
using Parking.Interfaces;
using Microsoft.AspNetCore.Authorization;
using System;

namespace Parking.Controllers
{
    [Authorize]
    public class ManageUserAssignmentsToParkingController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;
        IParkingManagement _parkingManagementManager;
        IParkingDetailsOnDate _parkingDetailsManager;
        IParking _parkingManager;

        public ManageUserAssignmentsToParkingController(ApplicationDbContext context, UserManager<User> userManager, IParkingManagement parkingManagementManager, IParkingDetailsOnDate parkingDetailsManager, IParking parkingManager)
        {
            _context = context;
            _userManager = userManager;
            _parkingManagementManager = parkingManagementManager;
            _parkingDetailsManager = parkingDetailsManager;
            _parkingManager = parkingManager;
        }

        public async Task<IActionResult> Index()
        {
            var DBRecords = await GetDataOfAllUsers();
            var model = await BuildModelWithDBValues(DBRecords.OrderBy(x => x.ParkingDetailsOnDate.Date).ThenBy(x => x.ParkingSpot.SpaceNumber));

            return View(model);
        }

        public async Task<IEnumerable<ParkingAndDateRelationship>> GetDataOfAllUsers()
        {
            DateTime StopGettingRecordsAt = DateTime.Now.AddDays(15);
            return await _parkingManagementManager.GetAllTheRecordsFromTodayToAsync(StopGettingRecordsAt);
        }

        public async Task<List<IGrouping<string, SpaceAndUserAssignmentIndex>>> BuildModelWithDBValues(IEnumerable<ParkingAndDateRelationship> parkingRecords)
        {
            var model = new List<SpaceAndUserAssignmentIndex>();
            var currentUser = GetCurrentUser(_userManager);
            var assignedParking = await _parkingManager.GetSingleParkingWithUserID(currentUser.Id);

            foreach (var item in parkingRecords)
            {
                var modelToAdd = new SpaceAndUserAssignmentIndex()
                {
                    ID = item.ID,
                    AssignedDate = item.ParkingDetailsOnDate.Date.ToShortDateString(),
                    AssignSpaceNumber = item.ParkingSpot.SpaceNumber,
                    AssignedUser = item.AssignedToUser?.Email,
                    Description = item.ParkingDetailsOnDate.Description,
                    DoesThisSpaceBelongToUser = item.ParkingSpot.SpaceNumber == assignedParking?.SpaceNumber
                };

                model.Add(modelToAdd);
            }

            return model.GroupBy(x => x.AssignedDate).ToList();
        }

        public async Task<IActionResult> Edit(int id)
        {
            var parkingRelationshipRecords = await _parkingManagementManager.GetByIdAsync(id);
            var model = PopulateEditModelWithDBRecords(parkingRelationshipRecords);

            return View(model);
        }

        private EditParkingUserAssignment PopulateEditModelWithDBRecords(ParkingAndDateRelationship parkingRelationshipRecords)
        {
            var applyPartialBooking = string.IsNullOrEmpty(parkingRelationshipRecords.ParkingDetailsOnDate.Description) ? false
                : parkingRelationshipRecords.ParkingDetailsOnDate.ApplyPartialBooking;

            var model = new EditParkingUserAssignment()
            {
                AssignToUserID = parkingRelationshipRecords.AssignedToUserID,
                ParkingNumberID = parkingRelationshipRecords.ParkingSpot.SpaceNumber,
                AssingOnDate = parkingRelationshipRecords.ParkingDetailsOnDate.Date,
                Description = parkingRelationshipRecords.ParkingDetailsOnDate.Description,
                ApplyPartialBooking = parkingRelationshipRecords.ParkingDetailsOnDate.ApplyPartialBooking,
                StartTimeIfPartial = parkingRelationshipRecords.ParkingDetailsOnDate.StartTimeIfPartial,
                EndTimeIfPartial = parkingRelationshipRecords.ParkingDetailsOnDate.EndTimeIfPartial
            };

            model = PopulateSelectLists(model);
            return model;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditParkingUserAssignment model)
        {
            if (ModelState.IsValid)
            {
                var ParkingAndDateRelationship = await _parkingManagementManager.GetByID(model.ID);

                ParkingAndDateRelationship.ParkingDetailsOnDate.Date = model.AssingOnDate;
                ParkingAndDateRelationship.ParkingDetailsOnDate.Description = model.Description;
                ParkingAndDateRelationship.ParkingID = model.ParkingNumberID;
                ParkingAndDateRelationship.AssignedToUser = null;
                ParkingAndDateRelationship.AssignedToUserID = model.AssignToUserID;
                ParkingAndDateRelationship.ParkingDetailsOnDate.ApplyPartialBooking = model.ApplyPartialBooking;
                ParkingAndDateRelationship.ParkingDetailsOnDate.StartTimeIfPartial = model.StartTimeIfPartial;
                ParkingAndDateRelationship.ParkingDetailsOnDate.EndTimeIfPartial = model.EndTimeIfPartial;

                await _parkingManagementManager.UpdateAndSave(ParkingAndDateRelationship);

                return RedirectToAction(nameof(Index));
            }

            model = PopulateSelectLists(model);

            return View(model);
        }

        public EditParkingUserAssignment PopulateSelectLists(EditParkingUserAssignment model)
        {
            model.AssignToUser = new SelectList(_context.Set<User>(), "Id", "Email");
            model.ParkingNumberToSelect = new SelectList(_context.Set<ParkingSpot>(), "ID", "SpaceNumber");

            return model;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateAssignedUser(int ID)
        {
            var fAParkingAndDateRelationship = await _context.ParkingAndDateRelationship.FirstOrDefaultAsync(x => x.ID == ID);

            var userId = GetCurrentUser(_userManager).Id;
            fAParkingAndDateRelationship.AssignedToUserID = userId;

            _context.Update(fAParkingAndDateRelationship);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FreeParking(int ID)
        {
            var fAParkingAndDateRelationship = await _context.ParkingAndDateRelationship.FirstOrDefaultAsync(x => x.ID == ID);

            fAParkingAndDateRelationship.AssignedToUserID = null;

            _context.Update(fAParkingAndDateRelationship);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

Parking/Views/Home/Index.cshtml
@model List<Parking.Models.SpaceAndUserAssignmentIndex>

@{
    ViewData["Title"] = "Index";
}

<p>You can see more details and days in advance by clicking in <a asp-area="" asp-controller="ManageUserAssignmentsToParking" asp-action="Index">Management</a></p>
<br />
<br />
<br />


<div class="columns">
    <h1><b>Today</b></h1>
</div>

<div class="row row--1">
    <div class="parking-spaces columns is-desktop is-mobile is-gapless is-multiline">
        @foreach (var item in Model)
        {
            @if (item.CanThisUserfreeThisSpace)
            {
                <div class="parking-space column is-1">
                    <form asp-action="FreeParking" asp-controller="ManageUserAssignmentsToParking" method="post" data-ajax="true" data-ajax-method="post">
                        <input asp-for="@item.ID" name="ID" type="hidden" class="form-control">
                        <input type="checkbox" onChange="this.form.submit()" checked id="@item.ID" />
                        @if (item.isThisSpacePArtiallybookedToday)
                        {
                    <label class="partially-booked" for="@item.ID"> @item.AssignSpaceNumber <br/> must free by @item.StartTimeIfPartial.Value.ToString(@"hh\:mm")</label>
                        }
                        else
                        {
                            <label for="@item.ID">@item.AssignSpaceNumber</label>
                        }
                    </form>
                </div>
            }
            else if (!string.IsNullOrEmpty(item.AssignedUser) || !string.IsNullOrEmpty(item.Description))
            {
                @if (item.isThisSpacePArtiallybookedToday)
                {
                    <div class="parking-space column is-1">
                        <form onclick="this.submit()" asp-action="UpdateAssignedUser" asp-controller="ManageUserAssignmentsToParking" method="post" data-ajax="true" data-ajax-method="post">
                            <input asp-for="@item.ID" name="ID" type="hidden" class="form-control">
                            <input type="checkbox" id="@item.ID" />
                            <label class="partially-booked" for="">
                                @item.AssignSpaceNumber  <br />
                                Booked for<br />
                                @item.StartTimeIfPartial.Value.ToString(@"hh\:mm")-@item.EndTimeIfPartial.Value.ToString(@"hh\:mm")
                            </label>
                        </form>
                    </div>
                }
                else
                {
                    <div class="parking-space column is-1">
                        <input type="checkbox" disabled checked id="@item.ID" />
                        <label for="@item.ID">@item.AssignSpaceNumber</label>
                    </div>
                }
            }
            else if (!Model.Any(x => x.CanThisUserfreeThisSpace))
            {
                <div class="parking-space column is-1">
                    <form onclick="this.submit()" asp-action="UpdateAssignedUser" asp-controller="ManageUserAssignmentsToParking" method="post" data-ajax="true" data-ajax-method="post">
                        <input asp-for="@item.ID" name="ID" type="hidden" class="form-control">
                        <input type="checkbox" id="@item.ID" />
                        <label for="">
                            @item.AssignSpaceNumber
                        </label>
                    </form>
                </div>
            }
            else
            {
                <div class="parking-space column is-1">
                    <input type="checkbox" id="@item.ID" />
                    <label for="">@item.AssignSpaceNumber</label>
                </div>
            }
        }

    </div>
</div>

@if (!Model.Any())
{
    <p>The list of days is empty, an administrator must add more days</p>
}