Parking/Controllers/ManageParkingSpaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Parking.EF;
using Parking.Entities;
using Parking.Models;
using Parking.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Parking.Code;
using ApplicationSettings;

namespace Parking.Controllers
{
    [Authorize]
    public class ManageParkingSpaceController : Controller
    {
        ManageAutomaticParkingDates CheckCurrentDays = new ManageAutomaticParkingDates();
        private readonly ApplicationDbContext _context;
        IParking _parkingManager;
        IParkingManagement _parkingManagementManager;
        IParkingDetailsOnDate _parkingDetailsManager;


        public ManageParkingSpaceController(ApplicationDbContext context, IParkingManagement parkingManagementManager, IParking parkingManager, IParkingDetailsOnDate parkingDetailsManager)
        {
            _context = context;
            _parkingManagementManager = parkingManagementManager;
            _parkingManager = parkingManager;
            _parkingDetailsManager = parkingDetailsManager;
        }

        public async Task<IActionResult> Index()
        {
            var databaseRecords = await _parkingManager.GetAllParkingSpaces();
            var model = PopulateIndexModelWithDatabaseRecods(databaseRecords);

            return View(model);
        }

        private List<ParkingIndexViewModel> PopulateIndexModelWithDatabaseRecods(IEnumerable<ParkingSpot> records)
        {
            var model = new List<ParkingIndexViewModel>();

            foreach (var item in records)
            {
                var toAddToModel = new ParkingIndexViewModel()
                {
                    ParkingID = item.ID,
                    ParkingNumber = item.SpaceNumber,
                    PermanentlyAssignToUser = item.PermanentlyAssignedToUser?.Email
                };

                model.Add(toAddToModel);
            }

            return model;
        }

        public IActionResult Create()
        {
            var model = new CreateParkingViewModel()
            {
                AssignToUser = new SelectList(_context.Set<User>(), "Id", "Email")
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateParkingViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _parkingManager.CreateAndSaveParkingSpaceAsync(model.PermanentlyAssignedToUserId, model.SpaceNumber);
                await CheckCurrentDays.CreateNextParkingDaysIfNeccesary(0, _parkingManager, _parkingDetailsManager, _parkingManagementManager);

                return RedirectToAction(nameof(Index));
            }

            model.AssignToUser = new SelectList(_context.Set<User>(), "Id", "Email");
            return View(model);
        }

        public async Task<EditParkingViewModel> CreateParkingModelWithDBRecords(ParkingSpot faParking)
        {
            var model = new EditParkingViewModel()
            {
                AssignToUser = new SelectList(_context.Set<User>(), "Id", "Email"),
                ID = faParking.ID,
                PermanentlyAssignedToUserId = faParking.PermanentlyAssignedToUserId,
                SpaceNumber = faParking.SpaceNumber
            };

            return model;
        }

        public async Task<IActionResult> Edit(int id)
        {
            var faParking = await _parkingManager.GetParkingByID(id);
            var model = await CreateParkingModelWithDBRecords(faParking);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditParkingViewModel model)
        {
            if (ModelState.IsValid)
            {
                var fAParking = await _parkingManager.GetParkingByID(model.ID);

                await FreeParkingSpaceFromPreviousOwner(fAParking, model);
                await AddNewOwnerToParkingSpace(fAParking, model);

                return RedirectToAction(nameof(Index));
            }

            model.AssignToUser = new SelectList(_context.Set<User>(), "Id", "Email");
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ConstantRoles.AdministratorRole)]
        public async Task<IActionResult> CreateMoreParkingDaysInAdvance()
        {
            int daysToAddInAdvance = 7;
            await CheckCurrentDays.CreateNextParkingDaysIfNeccesary(daysToAddInAdvance, _parkingManager, _parkingDetailsManager, _parkingManagementManager);
            return RedirectToAction("Index", "ManageUserAssignmentsToParking");
        }

        private async Task FreeParkingSpaceFromPreviousOwner(ParkingSpot fAParking, EditParkingViewModel model)
        {
            foreach (var item in fAParking.ParkingAndDateRelationship.ToList())
            {
                if (item.AssignedToUserID == item.ParkingSpot.PermanentlyAssignedToUserId || model.PermanentlyAssignedToUserId == null || item.AssignedToUserID == null)
                {
                    item.AssignedToUserID = model.PermanentlyAssignedToUserId;
                    await _parkingManagementManager.UpdateAndSave(item);
                }
            }
        }

        private async Task AddNewOwnerToParkingSpace(ParkingSpot fAParking, EditParkingViewModel model)
        {
            fAParking.SpaceNumber = model.SpaceNumber;
            fAParking.PermanentlyAssignedToUserId = model.PermanentlyAssignedToUserId;
            await _parkingManager.UpdateAndSaveAsync(fAParking);
        }

    }
}

Parking/Views/Shared/_Layout.cshtml
@using ApplicationSettings;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - F1rstParking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/bulma/bulma.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3 header-color">
            <div class="container">
                <a class="has-text-white-bis" asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/images/Logo.png" width="200" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link has-text-white-bis" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(ConstantRoles.AdministratorRole))
                        {
                            <li class="nav-item">
                                <a class="nav-link has-text-white-bis" asp-area="" asp-controller="ManageParkingSpace" asp-action="Index">Manage parking spaces</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link has-text-white-bis" asp-area="" asp-controller="ManageUserAssignmentsToParking" asp-action="Index">Full Details list</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                2019 -
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>